dnsservers:
  vars:
    ansible_ssh_become: yes
    ansible_become: yes
    ansible_ssh_user: ansible_user
    ansible_ssh_private_key_file: keys/ansible_user
    ansible_connection: ssh
    ansible_become_method: sudo
  children:
    cleversite_dns:
      hosts:      
        172.20.1.230


